In [165]:
import numpy as np
B = tuple([int(i) for i in input("Enter your begining vertex ").split(",")])
E = tuple([int(i) for i in input("Enter your end vertex ").split(",")])
grid = np.zeros((10,10)).astype(int)

grid[B] = "-1"
grid[E] = "-2"

def neighbour(grid,pos):
    x1,y1,x2,y2 = limit(grid,*pos)
    x1,y1,x2,y2 = limit(grid,*pos)
    index,val = [],[]
    for x in range(x1, x2):
        for y in range(y1, y2):
            if ((x,y) != pos and (x,y) != "" and grid[x,y] ==0) or ((x,y) != pos and grid[x,y] == -2):
                index.append((x,y))
                val.append(grid[x,y])
            elif (x,y) == pos:
                cval = grid[x,y]
    return index,val,cval
    
def limit(grid,x,y):
    x1,x2,y1,y2 = x-1,x+2,y-1,y+2
    x_max = grid.shape[0]
    y_max = grid.shape[1]
    if x1<0:
        x1= 0
    if x2> x_max:
        x2 = x_max
    if y1<0:
        y1= 0
    if y2> y_max:
        y2 = y_max
    return x1,y1,x2,y2
    
def adder(grid,pos):
    index,val,cval = neighbour(grid,pos)
    if cval<0:
        cval = 0
    for i in range(len(val)):
        if val[i] == 0:
            grid[index[i]] = cval+1
    return index,val
    
def pathfinder(grid,pos):
        value = [1]
        while -2 not in value:
            li = []
            value = []
            for i in pos:
                ind,val = adder(grid,i)
                li +=ind
                value+=val
                if -2 in value:
                    break
            pos = li
  

grid[0:6,5] = -3
        
print(grid,end="\n\n")

Enter your begining vertex 0,1
Enter your end vertex 4,7
[[ 0 -1  0  0  0 -3  0  0  0  0]
 [ 0  0  0  0  0 -3  0  0  0  0]
 [ 0  0  0  0  0 -3  0  0  0  0]
 [ 0  0  0  0  0 -3  0  0  0  0]
 [ 0  0  0  0  0 -3  0 -2  0  0]
 [ 0  0  0  0  0 -3  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]]



In [166]:
Origin_grid = grid.copy()
pos = [B]
pathfinder(grid,pos)
print(grid)

[[ 1 -1  1  2  3 -3  0  0  0  0]
 [ 1  1  1  2  3 -3  0  0  0  0]
 [ 2  2  2  2  3 -3  0  0  0  0]
 [ 3  3  3  3  3 -3  0  0  0  0]
 [ 4  4  4  4  4 -3  8 -2  0  0]
 [ 5  5  5  5  5 -3  7  8  0  0]
 [ 6  6  6  6  6  6  7  8  0  0]
 [ 7  7  7  7  7  7  7  0  0  0]
 [ 8  8  8  8  8  8  8  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]]


In [167]:
def backtrack(grid,pos):
    x1,y1,x2,y2 = limit(grid,*pos)
    index,val = [],[]
    for x in range(x1,x2):
        for y in range(y1,y2):
            if (x,y) != pos and grid[x,y] !=0 and grid[x,y] != -2 and grid[x,y] != -3:
                index.append((x,y))
                val.append(grid[x,y])
    return index,val
   

In [168]:
def findingPath(grid,pos):
    if grid[pos] == -1:
        return 0
    index,val = backtrack(grid,pos)
    min_v = min(val)
    i = val.index(min_v)
    pos = index[i]
    print(pos,min_v)
    Origin_grid[pos] = min_v
    findingPath(grid,pos)

In [169]:
findingPath(grid,E)

(5, 6) 7
(6, 5) 6
(5, 4) 5
(4, 3) 4
(3, 2) 3
(2, 1) 2
(1, 0) 1
(0, 1) -1


In [170]:
import pandas as pd
Origin_table = pd.DataFrame(Origin_grid)

In [172]:
Origin_table.replace({-1:"B",-2:"E", 0:" ",-3:"X"})

0  1  2  3  4  5  6  7  8  9
0     B           X            
1  1              X            
2     2           X            
3        3        X            
4           4     X     E      
5              5  X  7         
6                 6            
7                              
8                              
9