In [69]:
import numpy as np

grid = np.zeros((10,10)).astype(int)
print(grid)
grid[0:6,5] = -3


B = tuple([int(i) for i in input("Enter your begining vertex ").split(",")])
E = tuple([int(i) for i in input("Enter your end vertex ").split(",")])

grid[B] = "-1"
grid[E] = "-2"


def neighbour(grid,pos):
    x1,y1,x2,y2 = limit(grid,*pos)
    x,y = pos
    index,val = [],[]
    a,b,c,d = (x,y1),(x1,y),(x,y2),(x2,y)
    for i in [a,b,c,d]:
        if (i != pos  and grid[i] == 0) or (i != pos and grid[i] == -2):
            index.append(i)
            val.append(grid[i])
    cval = grid[pos]
    return index,val,cval
    
def limit(grid,x,y):
    x1,x2,y1,y2 = x-1,x+1,y-1,y+1
    x_max = grid.shape[0]
    y_max = grid.shape[1]
    if x1<0:
        x1= 0
    if x2>= x_max:
        x2 = x_max -1
    if y1<0:
        y1= 0
    if y2>= y_max:
        y2 = y_max - 1
    return x1,y1,x2,y2
    
def adder(grid,pos):
    index,val,cval = neighbour(grid,pos)
    if cval<0:
        cval = 0
    for i in range(len(val)):
        if val[i] == 0:
            grid[index[i]] = cval+1
    return index,val
    
def pathfinder(grid,pos):
        value = [1]
        while -2 not in value:
            li = []
            value = []
            for i in pos:
                ind,val = adder(grid,i)
                li +=ind
                value+=val
                if -2 in value:
                    break
            pos = li
  

        
print(grid,end="\n\n")

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
Enter your begining vertex 1,1
Enter your end vertex 6,7
[[ 0  0  0  0  0 -3  0  0  0  0]
 [ 0 -1  0  0  0 -3  0  0  0  0]
 [ 0  0  0  0  0 -3  0  0  0  0]
 [ 0  0  0  0  0 -3  0  0  0  0]
 [ 0  0  0  0  0 -3  0  0  0  0]
 [ 0  0  0  0  0 -3  0  0  0  0]
 [ 0  0  0  0  0  0  0 -2  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]]



In [60]:
Origin_grid = grid.copy()
pos = [B]
pathfinder(grid,pos)
grid

array([[ 2,  1,  2,  3,  4, -3,  0,  0,  0,  0],
       [ 1, -1,  1,  2,  3, -3,  0,  0,  0,  0],
       [ 2,  1,  2,  3,  4, -3,  0,  0,  0,  0],
       [ 3,  2,  3,  4,  5, -3,  0,  0,  0,  0],
       [ 4,  3,  4,  5,  6, -3,  0,  0,  0,  0],
       [ 5,  4,  5,  6,  7, -3, -2,  0,  0,  0],
       [ 6,  5,  6,  7,  8,  9, 10, 11,  0,  0],
       [ 7,  6,  7,  8,  9, 10, 11,  0,  0,  0],
       [ 8,  7,  8,  9, 10,  0,  0,  0,  0,  0],
       [ 9,  8,  9, 10,  0,  0,  0,  0,  0,  0]])

In [61]:
def backtrack(grid,pos):
    x,y = pos
    x1,y1,x2,y2 = limit(grid,*pos)
    index,val = [],[]
    a,b,c,d = (x,y1),(x1,y),(x,y2),(x2,y)
    for i in [a,b,c,d]:
        if i != pos and grid[i] !=0 and grid[i] != -2 and grid[i] != -3:
            index.append(i)
            val.append(grid[i])
    return index,val
   

In [62]:
def findingPath(grid,pos):
    if grid[pos] == -1:
        return 0
    index,val = backtrack(grid,pos)
    min_v = min(val)
    i = val.index(min_v)
    pos = index[i]
    Origin_grid[pos] = min_v
    findingPath(grid,pos)

In [63]:
findingPath(grid,E)

In [64]:
import pandas as pd
Origin_table = pd.DataFrame(Origin_grid)

In [65]:
Origin_table.replace({-1:"B",-2:"E", 0:" ",-3:"X"})

0  1  2  3  4  5   6  7  8  9
0                 X             
1     B           X             
2     1           X             
3     2           X             
4     3           X             
5     4           X   E         
6     5  6  7  8  9  10         
7                               
8                               
9